apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: build-and-push
  namespace: argocd
spec:
  entrypoint: build-and-push
  templates:
  - name: build-and-push
    steps:
    - - name: git-clone
        template: git-clone
      - name: debug-list-files
        template: debug-list-files
      - name: build-image
        template: build-image

  - name: git-clone
    container:
      image: alpine/git
      command: ["/bin/sh", "-c"]
      args:
      - |
        GIT_TRACE=1 git clone https://github.com/sylvainkalache/deploy-buildpack-containerized-python-app-to-argo.git /app && ls -la /app
      volumeMounts:
      - name: app-source
        mountPath: /app

  - name: debug-list-files
    container:
      image: alpine
      command: ["/bin/sh", "-c"]
      args: ["ls -la /app"]
      volumeMounts:
      - name: app-source
        mountPath: /app

  - name: build-image
    container:
      image: buildpacksio/pack
      command: ["/bin/sh", "-c"]
      args:
      - |
        ls -la /app && pack build 172.31.17.128:5000/my-python-app:latest --path /app/ --builder paketobuildpacks/builder:base --publish --network host
      volumeMounts:
      - name: docker-sock
        mountPath: /var/run/docker.sock
      - name: app-source
        mountPath: /app
      workingDir: /app
      securityContext:
        privileged: true

  volumes:
  - name: docker-sock
    hostPath:
      path: /var/run/docker.sock
  - name: app-source
    emptyDir: {}

