apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: build-and-push
  namespace: argocd
spec:
  entrypoint: build-and-push
  volumeClaimTemplates:
  - metadata:
      name: workdir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
  templates:
  - name: build-and-push
    steps:
    - - name: git-clone
        template: git-clone
      - name: build-image
        template: build-image
        arguments:
          parameters:
          - name: COMMIT_SHA
            value: "{{steps.git-clone.outputs.result}}"

  - name: git-clone
    outputs:
      parameters:
      - name: COMMIT_SHA
        valueFrom:
          path: "/mnt/vol/commit-sha.txt"
    container:
      image: alpine/git
      command: ["/bin/sh", "-c"]
      args:
      - |
        GIT_TRACE=1 git clone https://github.com/sylvainkalache/deploy-buildpack-containerized-python-app-to-argo.git /mnt/vol/ && \
        cd /mnt/vol/ && COMMIT_SHA=$(git rev-parse --short HEAD) && \
        echo $COMMIT_SHA > /mnt/vol/commit-sha.txt
      volumeMounts:
 

