apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: build-and-push
  namespace: argocd
spec:
  entrypoint: build-and-push
  templates:
  - name: build-and-push
    steps:
    - - name: git-clone
        template: git-clone
      - name: build-image
        template: build-image

  - name: git-clone
    container:
      image: alpine/git
      command: ["/bin/sh", "-c"]
      args:
      - |
        GIT_TRACE=1 git clone https://github.com/sylvainkalache/deploy-buildpack-containerized-python-app-to-argo.git . && ls -la
      volumeMounts:
      - name: app-source
        mountPath: /app

  - name: build-image
    container:
      image: buildpacksio/pack
      command: ["pack", "build"]
      args:
      - |
        172.31.17.128:5000/my-python-app:latest --path . --builder paketobuildpacks/builder-jammy-base:base --publish --network host
      volumeMounts:
      - name: docker-sock
        mountPath: /var/run/docker.sock
      - name: app-source
        mountPath: /app
      workingDir: /app
      securityContext:
        privileged: true

  volumes:
  - name: docker-sock
    hostPath:
      path: /var/run/docker.sock
  - name: app-source
    emptyDir: {}

